/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: HelloWorldData.h
  Source: /home/allen/ws/cyclonedds/install/share/CycloneDDS/examples/helloworld/HelloWorldData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_HELLOWORLDDATA_H_3D345830254758FD00D3D453C0A90FE1
#define DDSC_HELLOWORLDDATA_H_3D345830254758FD00D3D453C0A90FE1

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct HelloWorldData_Msg
{
  int32_t userID;
  char * message;
} HelloWorldData_Msg;

extern const dds_topic_descriptor_t HelloWorldData_Msg_desc;

#define HelloWorldData_Msg__alloc() \
((HelloWorldData_Msg*) dds_alloc (sizeof (HelloWorldData_Msg)));

#define HelloWorldData_Msg_free(d,o) \
dds_sample_free ((d), &HelloWorldData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_HELLOWORLDDATA_H_3D345830254758FD00D3D453C0A90FE1 */
